version: 1.0.{build}

branches:
  only:
    - appveyor-8.2.5

image: Visual Studio 2017

environment:
  nodejs_version: "6"
  nodejs_platform: "x64"

cache:
  - packages -> **\packages.config        # preserve NuGet packages in the root of build folder but will reset it if any packages.config file is modified
  - '%LocalAppData%\NuGet\Cache'          # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache'       # NuGet v3
  - node_modules -> package.json          # local npm modules
  - '%AppData%\npm-cache -> package.json' # npm cache
  - '%AppData%\npm -> package.json'       # npm global cache

install:
  - ps: Install-Product node $env:nodejs_version $env:nodejs_platform
  - npm install
  - npm install -g gulp
  - nuget install secure-file -ExcludeVersion -OutputDirectory .\packages
  - packages\secure-file\tools\secure-file -decrypt .\lib\license.xml.enc -secret "%LicenseEncryptionKey%"

build: off

before_test:
  - gulp Package-Build-Debug

test:
  assemblies:
    only:
      - \src\**\Tests\bin\**\Sitecore.*.Tests.dll

after_test:
  - gulp Package-Build-Release-For-Courier
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
          # Package for production
          $env:DEPLOY_ENVIRONMENT="production"
      } else {
          # Package for staging
          $env:DEPLOY_ENVIRONMENT="staging"
      }
  - ps: Copy-Item -Path ".\environments\$env:DEPLOY_ENVIRONMENT\App_Config" -Destination ".\temp" -Recurse -Force
  - .\lib\Sitecore.Courier\Sitecore.Courier.Runner.exe -t .\temp -o .\Habitat.update -r

artifacts:
  - path: Habitat.update
    name: Habitat Sitecore Update Package