version: 1.0.{build}

branches:
  only:
    - appveyor-8.2.5

image: Visual Studio 2017

environment:
  nodejs_version: "6"
  nodejs_platform: "x64"

cache:
  - packages -> **\packages.config        # preserve NuGet packages in the root of build folder but will reset it if any packages.config file is modified
  - '%LocalAppData%\NuGet\Cache'          # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache'       # NuGet v3
  - node_modules -> package.json          # local npm modules
  - '%AppData%\npm-cache -> package.json' # npm cache
  - '%AppData%\npm -> package.json'       # npm global cache

install:
  # Install required NodeJS version for Habitat
  - ps: Install-Product node $env:nodejs_version $env:nodejs_platform
  # Restore node modules
  - npm install
  # Install gulp
  - npm install -g gulp
  # Install secure-file
  - nuget install secure-file -ExcludeVersion -OutputDirectory .\packages
  # Decrypt the encrypted Sitecore license
  - packages\secure-file\tools\secure-file -decrypt .\lib\license.xml.enc -secret "%LicenseEncryptionKey%"

# Do not build using MsBuild
build: off

before_test:
  # Build projects in debug (including test projects)
  - gulp Package-Build-Debug

test:
  assemblies:
    only:
      # Run unit tests
      - \src\**\Tests\bin\**\Sitecore.*.Tests.dll

after_test:
  # Determine deployment environment
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
          # Package for production
          $env:DEPLOY_ENVIRONMENT="production"
      } else {
          # Package for staging
          $env:DEPLOY_ENVIRONMENT="staging"
      }
  # Build projects in release (excluding test projects) in /temp and package using Sitecore.Courier
  - gulp Package-Generate-With-Courier --env $env:DEPLOY_ENVIRONMENT
  # Create deployment artifact including update package and environment deployment scripts
  - 7z a Habitat.deployment.zip %APPVEYOR_BUILD_FOLDER%\Habitat.update %APPVEYOR_BUILD_FOLDER%\deployment\$env:DEPLOY_ENVIRONMENT\*

artifacts:
  - path: Habitat.deployment.zip
    name: HabitatDeploymentArchive

deploy: # Only run for staging builds
  - provider: Environment
    name: Habitat-Staging
    on:
      branch: appveyor-8.2.5
      appveyor_repo_tag: false

on_success:
  - ps: |
      if ($env:DEPLOY_ENVIRONMENT -eq "production") {
          # Only run for production builds
          Write-Host "Deploying to production..."
      }

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 5tB2yxNNtAeh5Qf6ElBKvUIJrRLitCLrmN82qnHGp5iRoQGud71J/EsiFy7zF61Uj18acJtOxV6dLTy+ZR95koi71iKkwNev7iLUuEmbgLE=